spring.application.name=scheduler
server.port=8083

# ADMIN PASSWORD
spring.security.user.password=password123

# POSTGRES DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/unitt_db
spring.datasource.username=acadschedule_user
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JSON DATE
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Kolkata
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# ==================== EMAIL CONFIG ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dummy@example.com
spring.mail.password=dummy_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
