spring.application.name=scheduler
server.port=${PORT:8083}


# ==================== SCHEDULE CONFIGURATION ====================
scheduler.grid.days=MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY
scheduler.grid.time-slots=09:00-09:40,09:40-10:30,10:30-10:45,10:45-11:35,11:35-12:25,12:25-01:15,LUNCH_BREAK,02:05-02:55,02:55-03:45,03:45-04:35
scheduler.grid.non-teachable-slots=2,6
scheduler.grid.valid-lab-starts=0,3,4,7,8

# ==================== POSTGRES DATABASE ====================
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.qjhyglosltbcfkhwxahg
spring.datasource.password=password123
spring.datasource.driver-class-name=org.postgresql.Driver


# HIKARI CONNECTION POOL LIMITS
spring.datasource.hikari.maximum-pool-size=4
spring.datasource.hikari.connection-test-query=SELECT 1
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Wait for Hibernate DDL before running data.sql
spring.jpa.defer-datasource-initialization=true


# JSON DATE
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=Asia/Kolkata
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss

# ==================== EMAIL CONFIG ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=eshanaaajith20@gmail.com
spring.mail.password=wvozgxreawbdwqjr
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.auth.mechanisms=LOGIN

# DEBUG MAILS
logging.level.org.springframework.mail=DEBUG

logging.file.name=application-debug.log
logging.level.org.springframework.web=DEBUG