spring.application.name=scheduler

server.port=${SERVER_PORT:8082}

spring.datasource.url=jdbc:postgresql://localhost:5432/unitt_db
spring.datasource.username=postgres
spring.datasource.password=Esha@123$

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
