name: Automated TT Generator CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Backend
        run: |
          cd Automated-Timetable-Scheduling-and-Faculty-Workload-Optimization-System/backend/scheduler
          mvn clean install -DskipTests

  frontend-admin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Automated-Timetable-Scheduling-and-Faculty-Workload-Optimization-System/frontend-admin
          npm install

      - name: Build frontend admin
        run: |
          cd Automated-Timetable-Scheduling-and-Faculty-Workload-Optimization-System/frontend-admin
          npm run build

  frontend-faculty:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd Automated-Timetable-Scheduling-and-Faculty-Workload-Optimization-System/frontend-faculty
          npm install

      - name: Build frontend faculty
        run: |
          cd Automated-Timetable-Scheduling-and-Faculty-Workload-Optimization-System/frontend-faculty
          npm run build
  

  deploy:
    needs: [backend, frontend-admin, frontend-faculty]
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend
        run: echo "Deploy backend to server"

      - name: Deploy frontend
        run: echo "Deploy frontend to hosting"